name: 'AST Metrics analysis'
description: 'Runs AST Metrics analysis on your project'
author: 'Jean-François Lépine'
branding:
  icon: bar-chart
  color: blue
runs:
  using: 'composite'
  
  steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Analyse
      run: |
        #!/bin/sh -l
        set -e

        # get version
        if [ -z "${AST_METRICS_VERSION}" ]; then
            # default to latest
            AST_METRICS_VERSION="latest"
        fi

        if [ "${AST_METRICS_VERSION}" = "latest" ]; then
            # get latest version from github
            VERSION=$(curl -s https://api.github.com/repos/halleck45/ast-metrics/releases/latest|grep tag_name|cut -d '"' -f 4)
        else
            # remove starting v if present
            AST_METRICS_VERSION=$(echo ${AST_METRICS_VERSION} | sed 's/^v//')
            VERSION=v{AST_METRICS_VERSION}
        fi

        # download and install
        curl -L https://github.com/Halleck45/ast-metrics/releases/download/${VERSION}/ast-metrics_Linux_x86_64 -o /usr/local/bin/ast-metrics
        chmod +x /usr/local/bin/ast-metrics

        # analyze
        if [[ -z "${DIRECTORY_TO_ANALYZE}" ]]; then
            echo "No path provided, using current directory"
            DIRECTORY_TO_ANALYZE="."
        fi

        if [[ -z "${REPORT_HTML_DIRECTORY}" ]]; then
            REPORT_HTML_DIRECTORY="ast-metrics-report"
        fi

        if [[ -z "${REPORT_MARKDOWN_FILENAME}" ]]; then
            REPORT_MARKDOWN_FILENAME="ast-metrics-report.md"
        fi

        # run
        /usr/local/bin/ast-metrics analyze \
            --non-interactive \
            --report-html=${REPORT_HTML_DIRECTORY} \
            --report-markdown=${REPORT_MARKDOWN_FILENAME} \
            "${DIRECTORY_TO_ANALYZE}"

        echo Finished
      shell: bash
      env:
        AST_METRICS_VERSION: ${{ inputs.version }}
        DIRECTORY_TO_ANALYZE: ${{ inputs.directory }}
        REPORT_HTML_DIRECTORY: ${{ inputs.report_html_directory }}
        REPORT_MARKDOWN_FILENAME: ${{ inputs.report_markdown_filename }}
        HISTORY_MONTHS: ${{ inputs.months }}

    - name: Adding markdown
      shell: bash
      run: cat ${{ inputs.report_markdown_filename }} >> $GITHUB_STEP_SUMMARY
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.report_html_directory }}
        name: 'AST Metrics HTML report'


    - name: Analyze achives
      run: |
        #!/bin/sh -l
        set -e

        # remove previous artifacts
        if [ -d archives ]; then
            rm -rf archives
        fi
        if [ -d $REPORT_HTML_DIRECTORY ]; then
            rm -rf $REPORT_HTML_DIRECTORY
        fi
        if [ -f $REPORT_MARKDOWN_FILENAME ]; then
            rm -f $REPORT_MARKDOWN_FILENAME
        fi

        mkdir -p archives

        # only if HISTORY_MONTHS is set and greater than 1
        if [ -z "$HISTORY_MONTHS" ]  || [ $HISTORY_MONTHS -lt 1 ]; then
            echo "HISTORY_MONTHS must be set and greater than 1"
            exit 0
        fi

        current_branch=$(git rev-parse --abbrev-ref HEAD)
        # stop if git has modifications
        if [ -n "$(git status --porcelain)" ]; then
            echo "Git workspace is dirty. Please commit or stash your changes before running this script."
            exit 1
        fi


        # try to get the first commit of past month for HISTORY_MONTHS times
        for ((i=0; i<$HISTORY_MONTHS; i++)); do

            date=$(date -d "$(date +%Y-%m-15) -${i} month" +%Y-%m-01)
            echo
            echo "Looking for the first commit of $date"

            sha1=$(git log --reverse --after="$date" --until="$(date -d "$date +1 month" +%Y-%m-01)" --pretty=format:"%at %H" | head -n 1)

            if [ ! -z "$sha1" ]; then

                # checkout this
                current_month=$(date -d "@$(echo $sha1 | cut -d ' ' -f 1)" +%Y-%m)
                echo "- checkout $sha1 ($current_month)"
                git checkout $(echo $sha1 | cut -d ' ' -f 2)

                echo "- analyze $DIRECTORY_TO_ANALYZE"
                mkdir -p archives
                /usr/local/bin/ast-metrics analyze \
                    --non-interactive \
                    --report-markdown=archives/${current_month}.md \
                    "${DIRECTORY_TO_ANALYZE}"

            else
                echo "No commit found for $date"
            fi
        done

        # checkout back
        git checkout $current_branch

        echo Finished
      shell: bash
      env:
        DIRECTORY_TO_ANALYZE: ${{ inputs.directory }}
        HISTORY_MONTHS: ${{ inputs.months }}
        REPORT_HTML_DIRECTORY: ${{ inputs.report_html_directory }}
        REPORT_MARKDOWN_FILENAME: ${{ inputs.report_markdown_filename }}
      if: ${{ inputs.months }} > 0


    - name: Upload archives artifact
      uses: actions/upload-artifact@v4
      with:
        path: archives
        name: 'archives'
      if: ${{ inputs.months }} > 0

inputs:
  version:
    description: 'Version of AST Metrics to use'
    required: false
    default: 'latest'
  directory:
    description: 'Directory to analyze'
    required: false
    default: '.'
  report_html_directory:
    description: 'Directory to deploy the report'
    required: false
    default: 'ast-metrics-report'
  report_markdown_filename:
    description: Filename to save the markdown report.
    required: false
    default: 'ast-metrics-report.md'
  months:
    description: 'Number of months to analyze'
    required: false
    default: 0
  